include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-dynamic: true
  errors:
    # allow having TODOs in the code
    todo: ignore
  exclude:
    - lib/generated/**
    - lib/l10n/
    - lib/generated_plugin_registrant.dart
linter:
  rules:
    # STYLE
    - camel_case_types
    - camel_case_extensions
    - library_names
    - file_names
    - library_prefixes
    - curly_braces_in_flow_control_structures
    - avoid_field_initializers_in_const_classes
    - prefer_const_constructors
    - prefer_const_declarations
    - directives_ordering
    # - lines_longer_than_80_chars

    # DOCUMENTATION
    - slash_for_doc_comments
    - package_api_docs # prefer

    # USAGE
    - implementation_imports
    - avoid_relative_lib_imports # prefer
    - prefer_relative_imports # prefer
    - prefer_adjacent_string_concatenation
    - unnecessary_brace_in_string_interps # avoid
    - prefer_iterable_whereType
    - unnecessary_lambdas
    - prefer_equal_for_default_values
    - avoid_init_to_null
    - unnecessary_getters_setters
    - unnecessary_this
    - prefer_initializing_formals
    - type_init_formals
    - empty_constructor_bodies
    - unnecessary_new
    - unnecessary_const
    - avoid_catching_errors
    - use_rethrow_when_possible
    - avoid_print
    - avoid_unnecessary_containers
    - use_function_type_syntax_for_parameters
    - unnecessary_null_in_if_null_operators
    - valid_regexps
    - unrelated_type_equality_checks
    - unawaited_futures
    - recursive_getters
    - avoid_shadowing_type_parameters
    - use_full_hex_values_for_flutter_colors
    - prefer_generic_function_type_aliases
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_null_checks_in_equality_operators
    - avoid_return_types_on_setters
    - avoid_single_cascade_in_expression_statements
    - avoid_types_as_parameter_names
    - await_only_futures
    - empty_catches
    - no_duplicate_case_values
    - null_closures
    - omit_local_variable_types
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_contains
    - prefer_for_elements_to_map_fromIterable
    - prefer_if_null_operators
    - prefer_inlined_adds
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - prefer_spread_collections
    - sort_child_properties_last
    - unsafe_html


    # DESIGN
    - use_to_and_as_if_applicable # prefer
    - one_member_abstracts # avoid
    - prefer_final_fields # prefer
    - avoid_setters_without_getters
    - avoid_private_typedef_functions # prefer
    - hash_and_equals


